# Generated by Django 4.2.6 on 2024-12-30 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
        ("regions", "0001_initial"),
        ("similarity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name to identify this pipelines experiment",
                        max_length=64,
                        verbose_name="Experiment name",
                    ),
                ),
                (
                    "notify_email",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Send an email when the pipelines task is finished",
                        verbose_name="Notify by email",
                    ),
                ),
                (
                    "status",
                    models.CharField(default="PENDING", editable=False, max_length=20),
                ),
                ("is_finished", models.BooleanField(default=False, editable=False)),
                ("requested_on", models.DateTimeField(auto_now_add=True)),
                ("parameters", models.JSONField(null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipelines_tasks",
                        to="datasets.dataset",
                        verbose_name="Use existing dataset...",
                    ),
                ),
                (
                    "regions_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="regions.regions",
                        verbose_name="Use existing regions...",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "similarity_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="similarity.similarity",
                        verbose_name="Use existing similarity...",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_on"],
                "abstract": False,
            },
        ),
    ]
