# Generated by Django 4.2.16 on 2024-12-03 14:48

import datasets.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WatermarksSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(max_length=50, unique=True, verbose_name="UID"),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("downloaded", models.BooleanField(default=False)),
                ("size", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="WatermarkProcessing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name to identify this watermarks experiment",
                        max_length=64,
                        verbose_name="Experiment name",
                    ),
                ),
                (
                    "status",
                    models.CharField(default="PENDING", editable=False, max_length=20),
                ),
                ("is_finished", models.BooleanField(default=False, editable=False)),
                ("requested_on", models.DateTimeField(auto_now_add=True)),
                ("api_tracking_id", models.UUIDField(editable=False, null=True)),
                (
                    "image",
                    models.ImageField(
                        max_length=300,
                        upload_to=datasets.utils.PathAndRename("watermarks/queries/"),
                    ),
                ),
                (
                    "detect",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        verbose_name="Detect and crop watermarks in the image",
                    ),
                ),
                ("annotations", models.JSONField(blank=True, null=True)),
                (
                    "compare_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queries",
                        to="watermarks.watermarkssource",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_on"],
            },
        ),
    ]
