# Generated by Django 4.2.6 on 2024-03-26 15:32

import datasets.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SingleWatermarkDetection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="watermark",
                        help_text="Optional name to identify this clustering experiment",
                        max_length=64,
                        verbose_name="Experiment name",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=300,
                        upload_to=datasets.utils.PathAndRename("watermarks/queries/"),
                    ),
                ),
                ("annotations", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(default="PENDING", editable=False, max_length=20),
                ),
                ("is_finished", models.BooleanField(default=False, editable=False)),
                ("requested_on", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_on"],
            },
        ),
    ]
