# Generated by Django 4.2.11 on 2024-04-15 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("watermarks", "0002_watermarkprocessing_watermarkssource_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watermarkprocessing",
            name="compare_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="queries",
                to="watermarks.watermarkssource",
            ),
        ),
        migrations.AlterField(
            model_name="watermarkprocessing",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Optional name to identify this clustering experiment",
                max_length=64,
                verbose_name="Experiment name",
            ),
        ),
    ]
