# Generated by Django 4.2.16 on 2024-10-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watermarks", "0003_alter_watermarkprocessing_compare_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watermarkprocessing",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Optional name to identify this watermarks experiment",
                max_length=64,
                verbose_name="Experiment name",
            ),
        ),
    ]
