# Generated by Django 4.2.16 on 2025-01-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watermarks", "0004_alter_watermarkprocessing_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="watermarkprocessing",
            name="parameters",
            field=models.JSONField(null=True),
        ),
    ]
