# Generated by Django 4.2.16 on 2024-11-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0002_rename_zip_dataset_regions_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="regions",
            name="regions",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
