# Generated by Django 4.2.6 on 2024-11-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0004_switch_dataset_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regions",
            name="model",
        ),
    ]
