# Generated by Django 4.2.30 on 2026-07-16 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0006_dataset_metadata_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watermarks', '0010_alter_watermarkspipeline_analysis_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paleography',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Optional name to identify this paleography experiment', max_length=64, verbose_name='Experiment name')),
                ('notify_email', models.BooleanField(blank=True, default=True, help_text='Send an email when the paleography task is finished', verbose_name='Notify by email')),
                ('status', models.CharField(default='PENDING', editable=False, max_length=20)),
                ('is_finished', models.BooleanField(default=False, editable=False)),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('finished_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('parameters', models.JSONField(null=True)),
                ('api_tracking_id', models.UUIDField(editable=False, null=True)),
                ('transcriptions', models.JSONField(blank=True, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paleography_tasks', to='datasets.dataset', verbose_name='Use existing dataset...')),
                ('requested_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('watermarks_pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='watermarks.watermarkspipeline')),
            ],
            options={
                'verbose_name': 'Paléographie',
                'ordering': ['-requested_on'],
            },
        ),
    ]
