# Generated by Django 4.2.30 on 2026-07-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paleography', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paleography',
            options={'ordering': ['-requested_on'], 'verbose_name': 'Paleography'},
        ),
    ]
