# Generated by Django 4.2.30 on 2026-07-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paleography', '0002_alter_paleography_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paleography',
            name='transcriptions',
        ),
    ]
