#!/usr/bin/env python3
"""
Generates every .env of the project from the root .env (single source of truth).

    python scripts/generate_env.py [--mode local|dev|prod] [--yes]

Generated files (never edit them directly):
    front/.env   config as seen by the Django process
    docker/.env             config as seen by docker compose and the containers
(api/.env is generated by api/install.py, which the root install.py delegates to)

local = fully dockerized local setup, everything in Docker, zero prompt, app running at the end
dev   = services in Docker, frontend, API and Svelte installed on the host, then `python run.py`
prod  = fully dockerized prod setup, full prompts, app running at the end

adapted from: https://github.com/Aikon-platform/aikon/blob/main/scripts/generate_env.py
"""

import argparse
import os
import re
import shutil
import subprocess
import socket
import secrets
import sys
import platform
from pathlib import Path
from typing import Literal

# CONSTANTS ****************************************************

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / ".env.template"
ROOT_ENV = ROOT / ".env"

MODES = ("local", "dev", "prod")
AUTOGEN = ("POSTGRES_PASSWORD", "SECRET_KEY")

# containers always use these internal ports; the root .env ports are only
# the host-side mappings (see docker/compose*.yml)
INTERNAL_PORTS = {"DB_PORT": "5432", "REDIS_PORT": "6379"}

# cross-platform separator for multiple confs in COMPOSE_FILES 
# https://docs.docker.com/compose/how-tos/environment-variables/envvars/#compose_file
SEPARATOR = ";" if platform.system() == "Windows" else ":"

COMPOSE_FILES = {
    "dev":   f"compose.yml{SEPARATOR}compose.dev.yml",
    "local": f"compose.yml{SEPARATOR}compose.local.yml",
    "prod":  f"compose.yml{SEPARATOR}compose.prod.yml",
}

# variables prompted per mode; everything else keeps its default/current value
PROMPTED = {
    "local": ("POSTGRES_PASSWORD",),
    "dev": ("POSTGRES_PASSWORD", "MEDIA_ROOT"),
    "prod": (
        "POSTGRES_PASSWORD",
        "APP_NAME",
        "APP_LANG",
        "MEDIA_ROOT",
        "GEONAMES_USER",
        "PROD_URL",
        "PROD_API_URL",
        "POSTGRES_DB",
        "POSTGRES_USER",
        "EMAIL_HOST",
        "EMAIL_HOST_USER",
        "EMAIL_HOST_PASSWORD",
        "DEFAULT_FROM_EMAIL",
        "APP_LOGO",
        "SSL_CERTIFICATE",
        "SSL_KEY",
        "HTTP_PROXY",
        "HTTPS_PROXY",
        "NGINX_PORT",
    ),
}

HEADER = (
    "# GENERATED from {src} — do not edit.\n"
    "# Edit the root .env then rerun: python scripts/generate_env.py\n\n"
)

REQUIRED = {
    "front/.env": (
        "SECRET_KEY",
        "POSTGRES_DB",
        "POSTGRES_USER",
        "POSTGRES_PASSWORD",
        "DB_HOST",
        "DB_PORT",
        "REDIS_HOST",
        "REDIS_PORT",
        "REDIS_DB_INDEX",
        "API_URL",
        "BASE_URL",
        "MEDIA_DIR",        
    ),
    "docker/.env": (
        "DATA_FOLDER",
        "USERID",
        "COMPOSE_FILE",
        "NGINX_PORT",
        "NGINX_MAX_BODY_SIZE",
        "NGINX_TIMEOUT",
    ),
}

# UTILS ****************************************************


def parse_env(path: Path) -> dict:
    """
    parse a .env file at `path`
    returns {key: (value, description)}, in declaration order
    """
    entries, desc = {}, ""
    for line in path.read_text().splitlines():
        line = line.strip()
        if line.startswith("#"):
            desc = line.lstrip("# ").strip()
        elif "=" in line:
            key, _, val = line.partition("=")
            entries[key.strip()] = (val.strip().strip('"'), desc)
            desc = ""
    return entries


def next_free_port(port: str) -> int:
    port = int(port)
    while True:
        with socket.socket() as s:
            if s.connect_ex(("127.0.0.1", port)) != 0:
                return port
        port += 1


def ask_mode() -> str:
    current = parse_env(ROOT_ENV).get("MODE", ("", ""))[0] if ROOT_ENV.exists() else ""
    mode = (
        input(f"Install mode ({' / '.join(MODES)}) [{current or 'local'}]: ").strip()
        or current
        or "local"
    )
    if mode not in MODES:
        sys.exit(f"Invalid mode '{mode}'")
    return mode


def prompt(key: str, default: str, desc: str) -> str:
    hint = f" | {desc}" if desc else ""
    val = input(f"{key}{hint} (press Enter for default value)\n  [{default or 'empty'}]: ").strip()
    return default if not val else "" if val == "x" else val


# .ENV GENERATION ****************************************************

def resolve_values(mode: Literal["local","dev","prod"], assume_yes: bool) -> dict:
    """
    create a dict containing all .env variables and their values, 
    inheriting values from the existing .env and from .env.template  

    params:
        - mode: installation mode (influences the prompted variables)
        - assume_yes: don't prompt
    """
    env_template = parse_env(TEMPLATE)
    # dict representation `{var_name: val}` of the current .env file, if it exists
    env_current = (
        {k: v for k, (v, _) in parse_env(ROOT_ENV).items()} if ROOT_ENV.exists() else {}
    )
    fresh = not env_current
    # new environment currently being built
    v = {}

    for key, (default, desc) in env_template.items():
        val = env_current.get(key, default)
        if key == "MEDIA_ROOT":
            val = str(Path(val or ROOT / "data").resolve())
        if key in AUTOGEN and not val:
            val = secrets.token_urlsafe(40)
        if key in PROMPTED[mode]:
            if key == "POSTGRES_PASSWORD":
                val = prompt(key, val, desc)
            elif not assume_yes:
                val = prompt(key, val, desc)
        if key.endswith("_PORT") and mode != "prod" and key not in env_current:
            free = next_free_port(val)
            if free != int(val):
                print(f"⚠ port {val} busy → {key}={free} (set {key} in .env to override)", file=sys.stderr)
                val = free
        v[key] = str(val)

    v["MODE"] = mode

    if mode == "prod" and not (v["PROD_URL"] and v["PROD_API_URL"]):
        sys.exit("PROD_URL and PROD_API_URL are required in prod mode")

    if fresh:
        print(f"Creating {ROOT_ENV}")
    return v


def derive(v: dict, mode: str, in_docker: bool) -> dict:
    """set values that depend on the build context (host vs container)."""
    host = lambda svc: svc if in_docker else "localhost"
    port = lambda key: INTERNAL_PORTS[key] if in_docker else v[key]
    prod = mode == "prod"
    nginx = mode != "dev"  # nginx is the entrypoint whenever the front is containerized
    base = (
        f"https://{v['PROD_URL']}"
        if prod
        else f"http://localhost:{v['NGINX_PORT'] if nginx else v['FRONT_PORT']}"
    )

    return {
        "MODE": mode,
        "ALLOWED_HOSTS": "localhost,127.0.0.1,0.0.0.0,web,nginx,host.docker.internal",
        "DEBUG": str(not prod),
        "DOCKER": str(in_docker),
        "C_FORCE_ROOT": "True",
        "DB_HOST": host("db"),
        "DB_PORT": port("DB_PORT"),
        "REDIS_HOST": host("redis"),
        "REDIS_PORT": port("REDIS_PORT"),
        "REDIS_DB_INDEX": "2" if mode == "dev" else "0",
        "MEDIA_DIR": "/data/mediafiles" if in_docker else f"{v['MEDIA_ROOT']}/mediafiles",
        "BASE_URL": base,
        "APP_URL_FROM_DOCKER": (
            base if prod
            else "http://web:8000" if in_docker
            else f"http://host.docker.internal:{v['FRONT_PORT']}"
        ),
        "APP_URL_FROM_API": (
            base if prod
            else "http://web:8000" if in_docker  # local: api container → web
            else f"http://localhost:{v['FRONT_PORT']}"  # dev: api on host → localhost
        ),
        "API_URL": v["PROD_API_URL"] if prod else f"http://{'api' if in_docker else 'localhost'}:{v['API_PORT']}",
    }


def write_root_env(v: dict) -> None:
    """Rewrites the root .env from the template using values from `v`, keeping comments and layout."""
    text = TEMPLATE.read_text()
    for key, val in v.items():
        text = re.sub(rf"^{key}=.*$", f"{key}={val}", text, flags=re.M)
    ROOT_ENV.write_text(text)


def write_env(path: Path, variables: dict) -> None:
    rel = str(path.relative_to(ROOT))
    missing = [k for k in REQUIRED.get(rel, ()) if not variables.get(k)]
    if missing:
        sys.exit(f"✗ {rel}: missing required keys {missing}")
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"{k}={v}" for k, v in variables.items()]
    path.write_text(HEADER.format(src=ROOT_ENV) + "\n".join(lines) + "\n")
    print(f"  wrote {path.relative_to(ROOT)}")


def generate_nginx_conf(v: dict) -> None:
    def apply_template(template: str) -> str:
        # replace all variables with values + rename file + write template to file
        text = template.read_text()
        for key in ("DJANGO_PORT", "PROD_URL", "NGINX_PORT", "NGINX_MAX_BODY_SIZE",
                    "NGINX_TIMEOUT", "SSL_CERTIFICATE", "SSL_KEY"):
            if val := v.get(key):
                text = text.replace(key, val)
        out = template.with_suffix("")  # nginx_external.conf.template → nginx_external.conf
        out.write_text(text)
        print(f"  wrote {out.relative_to(ROOT)}")

    if v["MODE"] == "dev":
        return
    elif v["MODE"] == "local":
        template = ROOT / "docker" / "web" / "nginx.conf.template"
        apply_template(template)
        text = template.read_text()
        return
    for template in (ROOT / "docker" / "web").glob("nginx_*.conf.template"):
        apply_template(template)


def generate(mode: str, assume_yes: bool) -> None:
    """
    generate and write:
    - the root .env 
    - all inherited .env files
    - nginx configs
    """
    v = resolve_values(mode, assume_yes)
    write_root_env(v)

    front_in_docker = mode != "dev"

    # front: perspective of the Django process (container in local/prod, host in dev)
    write_env(ROOT / "front/.env", v | derive(v, mode, front_in_docker))

    # cantaloupe: always a container
    d = derive(v, mode, in_docker=True)

    # docker: perspective of compose and of every container (redis, db...).
    # host-side ports are re-applied on top: compose uses them for port mappings.
    # NOTE: `dict1 | dict2` computes the UNION of dict1 and dict2   
    write_env(
        ROOT / "docker/.env",
        v
        | d
        | {k: v[k] for k in INTERNAL_PORTS}
        | {
            "USERID": os.getuid() if hasattr(os, "getuid") else 1000,
            "DATA_FOLDER": v["MEDIA_ROOT"],
            "WEB_HOST": "web" if front_in_docker else "host.docker.internal",
            "COMPOSE_FILE": COMPOSE_FILES[mode],
            "COMPOSE_PATH_SEPARATOR": ":",
            "COMPOSE_PROFILES": "front" if front_in_docker else "",
        },
    )

    (Path(v["MEDIA_ROOT"]) / "mediafiles/img").mkdir(parents=True, exist_ok=True)

    generate_nginx_conf(v)

    print(f"✅ .env files generated (mode: {mode})")
    return v


# ENTRYPOINT ****************************************************

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mode", choices=MODES)
    parser.add_argument("--yes", action="store_true", help="never prompt, use defaults")
    args = parser.parse_args()
    generate(args.mode or ask_mode(), args.yes)
