# Generated by Django 4.2.6 on 2024-12-30 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0001_initial"),
        ("similarity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="similarity",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="similarity_tasks",
                to="pipelines.pipeline",
            ),
        ),
    ]
