# Generated by Django 4.2.16 on 2024-11-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("similarity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="similarity",
            name="algorithm",
            field=models.CharField(default="cosine", max_length=20),
        ),
        migrations.AlterField(
            model_name="similarity",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Optional name to identify this similarity experiment",
                max_length=64,
                verbose_name="Experiment name",
            ),
        ),
        migrations.AlterField(
            model_name="similarity",
            name="notify_email",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Send an email when the similarity task is finished",
                verbose_name="Notify by email",
            ),
        ),
    ]
