# Generated by Django 4.2.6 on 2024-11-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("similarity", "0003_alter_similarity_dataset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="similarity",
            name="algorithm",
        ),
    ]
