# Generated by Django 4.2.6 on 2024-11-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0005_remove_regions_model"),
        ("similarity", "0004_remove_similarity_algorithm"),
    ]

    operations = [
        migrations.AddField(
            model_name="similarity",
            name="crops",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="similarity_crops",
                to="regions.regions",
                verbose_name="Use crops from...",
            ),
        ),
    ]
