# Generated by Django 4.2.6 on 2023-10-20 14:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTIClustering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notify_email', models.EmailField(help_text='Email address to notify you about the clustering progress', max_length=254, verbose_name='Email address to notify')),
                ('status', models.CharField(default='PENDING', editable=False, max_length=20)),
                ('is_finished', models.BooleanField(default=False, editable=False)),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('api_tracking_id', models.UUIDField(editable=False, null=True)),
                ('parameters', models.JSONField(null=True)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datasets.zippeddataset')),
            ],
            options={
                'ordering': ['-requested_on'],
            },
        ),
    ]
