# Generated by Django 4.2.6 on 2023-11-10 16:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DTIClustering",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="dti",
                        help_text="An optional name to identify this clustering",
                        max_length=64,
                        verbose_name="Clustering name",
                    ),
                ),
                (
                    "notify_email",
                    models.EmailField(
                        help_text="Email address to notify you about the clustering progress",
                        max_length=254,
                        verbose_name="Email address to notify",
                    ),
                ),
                (
                    "status",
                    models.CharField(default="PENDING", editable=False, max_length=20),
                ),
                ("is_finished", models.BooleanField(default=False, editable=False)),
                ("requested_on", models.DateTimeField(auto_now_add=True)),
                ("api_tracking_id", models.UUIDField(editable=False, null=True)),
                ("parameters", models.JSONField(null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="datasets.zippeddataset",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_on"],
            },
        ),
        migrations.CreateModel(
            name="SavedClustering",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="dti",
                        help_text="An optional name to identify this clustering",
                        max_length=64,
                        verbose_name="Clustering name",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                ("clustering_data", models.JSONField(null=True)),
                (
                    "from_dti",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_clustering",
                        to="dticlustering.dticlustering",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manual clustering",
                "ordering": ["-date"],
            },
        ),
    ]
