# Generated by Django 4.2.6 on 2023-10-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dticlustering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dticlustering',
            name='name',
            field=models.CharField(blank=True, default='dti', help_text='An optional name to identify this clustering', max_length=64, verbose_name='Clustering name'),
        ),
    ]
