# Generated by Django 4.2.11 on 2024-03-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dticlustering", "0002_alter_dticlustering_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dticlustering",
            name="name",
            field=models.CharField(
                blank=True,
                default="dti",
                help_text="Optional name to identify this clustering experiment",
                max_length=64,
                verbose_name="Experiment name",
            ),
        ),
        migrations.AlterField(
            model_name="dticlustering",
            name="notify_email",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Send an email when the clustering is finished",
                verbose_name="Notify by email",
            ),
        ),
    ]
