# Generated by Django 4.2.6 on 2023-10-30 20:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dticlustering', '0002_dticlustering_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedClustering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('clustering_data', models.JSONField(null=True)),
                ('from_dti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dticlustering.dticlustering')),
            ],
            options={
                'verbose_name': 'Manual clustering',
                'ordering': ['-date'],
            },
        ),
    ]
