# Generated by Django 4.2.6 on 2024-04-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dticlustering", "0003_alter_dticlustering_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dticlustering",
            options={
                "ordering": ["-requested_on"],
                "permissions": [
                    ("monitor_dticlustering", "Can monitor DTI Clustering")
                ],
                "verbose_name": "DTI Clustering",
            },
        ),
    ]
