# Generated by Django 4.2.11 on 2024-04-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dticlustering", "0004_alter_dticlustering_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dticlustering",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Optional name to identify this clustering experiment",
                max_length=64,
                verbose_name="Experiment name",
            ),
        ),
    ]
