# Generated by Django 4.2.16 on 2024-10-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dticlustering", "0005_alter_dticlustering_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dticlustering",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Optional name to identify this dti experiment",
                max_length=64,
                verbose_name="Experiment name",
            ),
        ),
        migrations.AlterField(
            model_name="dticlustering",
            name="notify_email",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Send an email when the dti task is finished",
                verbose_name="Notify by email",
            ),
        ),
    ]
