# Generated by Django 4.2.16 on 2024-10-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dticlustering", "0006_alter_dticlustering_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savedclustering",
            old_name="from_dti",
            new_name="from_task",
        ),
    ]
