# Generated by Django 4.2.6 on 2024-11-22 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datasets", "0007_alter_dataset_iiif_manifests"),
        ("dticlustering", "0007_rename_from_dti_savedclustering_from_task"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dticlustering",
            options={"verbose_name": "DTI Clustering"},
        ),
        migrations.AlterField(
            model_name="dticlustering",
            name="dataset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="datasets.dataset",
            ),
        ),
    ]
