# Generated by Django 4.2.6 on 2025-01-13 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0001_initial"),
        ("dticlustering", "0008_alter_dticlustering_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dticlustering",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dticlustering_tasks",
                to="pipelines.pipeline",
            ),
        ),
    ]
